/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as StockCountRouteImport } from './routes/stock-count'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReceivingRouteImport } from './routes/receiving'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as MasterItemsRouteImport } from './routes/master-items'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportExportRouteImport } from './routes/import-export'
import { Route as BeginningStockRouteImport } from './routes/beginning-stock'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const StockCountRoute = StockCountRouteImport.update({
  id: '/stock-count',
  path: '/stock-count',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivingRoute = ReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterItemsRoute = MasterItemsRouteImport.update({
  id: '/master-items',
  path: '/master-items',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportExportRoute = ImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginningStockRoute = BeginningStockRouteImport.update({
  id: '/beginning-stock',
  path: '/beginning-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beginning-stock': typeof BeginningStockRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/master-items': typeof MasterItemsRoute
  '/purchase': typeof PurchaseRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock-count': typeof StockCountRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beginning-stock': typeof BeginningStockRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/master-items': typeof MasterItemsRoute
  '/purchase': typeof PurchaseRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock-count': typeof StockCountRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beginning-stock': typeof BeginningStockRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/master-items': typeof MasterItemsRoute
  '/purchase': typeof PurchaseRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock-count': typeof StockCountRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beginning-stock'
    | '/import-export'
    | '/login'
    | '/master-items'
    | '/purchase'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/stock-count'
    | '/suppliers'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beginning-stock'
    | '/import-export'
    | '/login'
    | '/master-items'
    | '/purchase'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/stock-count'
    | '/suppliers'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/beginning-stock'
    | '/import-export'
    | '/login'
    | '/master-items'
    | '/purchase'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/stock-count'
    | '/suppliers'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeginningStockRoute: typeof BeginningStockRoute
  ImportExportRoute: typeof ImportExportRoute
  LoginRoute: typeof LoginRoute
  MasterItemsRoute: typeof MasterItemsRoute
  PurchaseRoute: typeof PurchaseRoute
  ReceivingRoute: typeof ReceivingRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StockCountRoute: typeof StockCountRoute
  SuppliersRoute: typeof SuppliersRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-count': {
      id: '/stock-count'
      path: '/stock-count'
      fullPath: '/stock-count'
      preLoaderRoute: typeof StockCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiving': {
      id: '/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof ReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-items': {
      id: '/master-items'
      path: '/master-items'
      fullPath: '/master-items'
      preLoaderRoute: typeof MasterItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-export': {
      id: '/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof ImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginning-stock': {
      id: '/beginning-stock'
      path: '/beginning-stock'
      fullPath: '/beginning-stock'
      preLoaderRoute: typeof BeginningStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeginningStockRoute: BeginningStockRoute,
  ImportExportRoute: ImportExportRoute,
  LoginRoute: LoginRoute,
  MasterItemsRoute: MasterItemsRoute,
  PurchaseRoute: PurchaseRoute,
  ReceivingRoute: ReceivingRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StockCountRoute: StockCountRoute,
  SuppliersRoute: SuppliersRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
