-- ============================================================================
-- 002_inventory_lots.sql
--
-- Purpose: FIFO lot tracking. Every unit of stock that enters the system
-- through a purchase or a beginning-stock entry gets its own lot, so
-- consumption can later be allocated oldest-first.
--
-- Backward compatibility: brand-new table, not read/written by the current
-- app. ON DELETE behavior mirrors existing schema conventions exactly
-- (item_id cascades like purchase_items.item_id already does; branch_id
-- and supplier_id set null like purchases.branch_id / items.supplier_id
-- already do) so existing deleteItem()/deleteSupplier() calls keep working.
-- ============================================================================

create table if not exists public.inventory_lots (
  id                uuid primary key default gen_random_uuid(),
  lot_number        text not null unique,
  branch_id         uuid references public.branches(id) on delete set null,
  item_id           uuid not null references public.items(id) on delete cascade,
  purchase_item_id  uuid references public.purchase_items(id) on delete set null,
  supplier_id       uuid references public.suppliers(id) on delete set null,
  received_date     date not null default current_date,
  expiry_date       date,
  unit_cost         numeric not null default 0,
  qty_received      numeric not null check (qty_received >= 0),
  qty_remaining     numeric not null check (qty_remaining >= 0),
  status            text not null default 'active'
                       check (status in ('active', 'depleted', 'expired', 'cancelled')),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint inventory_lots_remaining_lte_received check (qty_remaining <= qty_received)
);

comment on table public.inventory_lots is
  'One row per received/beginning lot of stock. Created automatically by '
  'fn_purchase_item_to_lot() (from purchase_items inserts) and '
  'fn_transaction_to_movement() (from transactions of type ''beginning''). '
  'Never written to directly by the application. qty_remaining is decremented '
  'exclusively by fn_consume_fifo(), which only runs when a stock_counts row '
  'is approved -- not on every stock decrease.';

comment on column public.inventory_lots.lot_number is
  'Globally unique, format LOT-YYYYMMDD-NNNN, generated by '
  'generate_lot_number(). Sequence resets daily and is serialized per-day '
  'via a session-level advisory lock to avoid collisions under concurrent '
  'inserts.';

comment on column public.inventory_lots.purchase_item_id is
  'NULL for lots created from a ''beginning'' transaction rather than a '
  'purchase. ON DELETE SET NULL so deleting the originating purchase line '
  'never destroys lot/FIFO history.';

comment on column public.inventory_lots.branch_id is
  'Nullable because purchases.branch_id and transactions.branch_id are '
  'themselves nullable in the current schema/app -- a lot created before '
  'the app always supplies a branch will simply be unattributed until '
  'backfilled.';
